=== AnthonyCC/sf-temp-ui/projects/CMS/src/com/freshdirect/cms/resource/CMS.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns="http://www.freshdirect.com/xsd/CMS" xmlns:cms="http://www.freshdirect.com/xsd/CMS" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.freshdirect.com/xsd/CMS" elementFormDefault="qualified" version="1.0">
	<xsd:annotation>
		<xsd:documentation xml:lang="en"> Schema describing FreshDirect
			storefront definitions and implementations Copyright 2004
			FreshDirect </xsd:documentation>
	</xsd:annotation>
	<!--
		
		Mix-in attribute groups

	-->
	<xsd:attributeGroup name="InheritableDef">
		<xsd:attribute name="inheritable" type="xsd:boolean" default="false"/>
		<xsd:attribute name="required" type="xsd:boolean" default="false"/>
		<xsd:attribute name="readOnly" type="xsd:boolean" default="false"/>
	</xsd:attributeGroup>
	<xsd:attributeGroup name="KeyedObjectDef">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="cardinality" use="optional" default="One">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="One">
						<xsd:annotation>
							<xsd:documentation>One: denotes that this property
								is single valued</xsd:documentation>
						</xsd:annotation>
					</xsd:enumeration>
					<xsd:enumeration value="Many">
						<xsd:annotation>
							<xsd:documentation>Many: denotes that this property
								is multi valued</xsd:documentation>
						</xsd:annotation>
					</xsd:enumeration>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:attributeGroup>
	<!--

		a simple type that defines mappings to common primitive types

	-->
	<xsd:simpleType name="PrimitiveType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="B">
				<xsd:annotation>
					<xsd:documentation>Boolean</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="I">
				<xsd:annotation>
					<xsd:documentation>Integer</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="D">
				<xsd:annotation>
					<xsd:documentation>Double</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="S">
				<xsd:annotation>
					<xsd:documentation>String</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="TXT">
				<xsd:annotation>
					<xsd:documentation>String</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="DT">
				<xsd:annotation>
					<xsd:documentation>Date</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!--

		a simple type that can be reused to define descriptions of definitions

	-->
	<xsd:simpleType name="DescriptionType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="128"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!--

		Base type consisting of zero or more elements

	-->
	<xsd:complexType name="BaseElementOnlyType" abstract="true" mixed="false"/>
	<!--

		Base type for attribute and relationship definitions

	-->
	<xsd:complexType name="BaseDefType" abstract="true" mixed="false">
		<xsd:complexContent mixed="false">
			<xsd:extension base="BaseElementOnlyType">
				<xsd:sequence>
					<xsd:element name="Description" type="DescriptionType" minOccurs="0"/>
				</xsd:sequence>
				<xsd:attributeGroup ref="KeyedObjectDef"/>
				<xsd:attributeGroup ref="InheritableDef"/>
				<xsd:attribute name="label" use="optional" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--
	
		definition of a content node
		
	-->
	<xsd:complexType name="ContentNodeDefType">
		<xsd:complexContent>
			<xsd:extension base="BaseElementOnlyType">
				<xsd:sequence>
					<xsd:element name="AttributeDefs">
						<xsd:complexType mixed="false">
							<xsd:complexContent mixed="false">
								<xsd:extension base="BaseElementOnlyType">
									<xsd:choice minOccurs="0" maxOccurs="unbounded">
										<xsd:element name="AttributeDef" type="AttributeDefType"/>
										<xsd:element name="EnumDef" type="EnumDefType"/>
									</xsd:choice>
								</xsd:extension>
							</xsd:complexContent>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="RelationshipDefs" minOccurs="0">
						<xsd:complexType mixed="false">
							<xsd:complexContent mixed="false">
								<xsd:extension base="BaseElementOnlyType">
									<xsd:sequence>
										<xsd:element name="RelationshipDef" type="RelationshipDefType" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:extension>
							</xsd:complexContent>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
				<xsd:attribute name="name" type="xsd:string"/>
				<xsd:attribute name="generateId" use="optional" default="false">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="false">
								<xsd:annotation>
									<xsd:documentation>Do not generate id automaticly</xsd:documentation>
								</xsd:annotation>
							</xsd:enumeration>
							<xsd:enumeration value="true">
								<xsd:annotation>
									<xsd:documentation>Generate id automaticly</xsd:documentation>
								</xsd:annotation>
							</xsd:enumeration>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

		Attribute type structure

	-->
	<xsd:complexType name="AttributeDefType">
		<xsd:complexContent>
			<xsd:extension base="BaseDefType">
				<xsd:attribute name="type" use="required" type="PrimitiveType"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

		EnumDef type structure

	-->
	<xsd:complexType name="EnumDefType">
		<xsd:complexContent>
			<xsd:extension base="AttributeDefType">
				<xsd:sequence>
					<xsd:element name="EnumValue" minOccurs="1" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:complexContent>
								<xsd:extension base="BaseElementOnlyType">
									<xsd:attribute name="value" use="required"/>
									<xsd:attribute name="label" use="required"/>
									<xsd:attribute name="description" use="optional" />
								</xsd:extension>
							</xsd:complexContent>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>


	<!--

		Relationship type structure

	-->
	<!-- definition of a relationship -->
	<xsd:complexType name="RelationshipDefType">
		<xsd:complexContent>
			<xsd:extension base="BaseDefType">
				<xsd:sequence>
					<xsd:element name="DestinationDef" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:complexContent>
								<xsd:extension base="BaseElementOnlyType">
									<xsd:attribute name="contentType"/>
									<xsd:attribute name="reverseAttributeName"/>
									<xsd:attribute name="reverseAttributeLabel"/>
								</xsd:extension>
							</xsd:complexContent>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
				<xsd:attribute name="navigable" type="xsd:boolean" use="optional" default="false"/>
				<xsd:attribute name="type" use="optional" default="A">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="C">
								<xsd:annotation>
									<xsd:documentation>Composition: denotes a
										"containment" or "whole-part" relationship</xsd:documentation>
								</xsd:annotation>
							</xsd:enumeration>
							<xsd:enumeration value="A">
								<xsd:annotation>
									<xsd:documentation>Aggregation: denotes a
										"refers to" relationsip</xsd:documentation>
								</xsd:annotation>
							</xsd:enumeration>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

		CMS definition structure

	-->
	<xsd:element name="CMSDef" type="CMSDefType">
		<!-- content type names are considered keys -->
		<xsd:key name="ContentTypeUniqueness">
			<xsd:selector xpath="ContentTypeDef"/>
			<xsd:field xpath="@name"/>
		</xsd:key>
		<!-- relationship destinations must be content types -->
		<xsd:keyref name="RelationshipEndpointDef" refer="ContentTypeUniqueness">
			<xsd:selector xpath="ContentTypeDef/RelationshipDefs/RealtionshipDef/Destination"/>
			<xsd:field xpath="@ref"/>
		</xsd:keyref>
	</xsd:element>
	<xsd:complexType name="CMSDefType" mixed="false">
		<xsd:complexContent mixed="false">
			<xsd:extension base="BaseElementOnlyType">
				<xsd:sequence>
					<xsd:element name="ContentTypeDef" type="ContentNodeDefType" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--
	
	
	
	
	








		CMS implementation structure

	-->
	<xsd:element name="CMSData" type="CMSDataType">
		<!-- content ids are considered keys -->
		<xsd:key name="ContentIdUniqueness">
			<xsd:selector xpath="ContentNode"/>
			<xsd:field xpath="@contentId"/>
		</xsd:key>
		<!-- relationship destinations must be content nodes-->
		<xsd:keyref name="RelationshipEndpoint" refer="ContentIdUniqueness">
			<xsd:selector xpath="ContentNode/Relationships/Realtionship/Destinations/Destination"/>
			<xsd:field xpath="@ref"/>
		</xsd:keyref>
	</xsd:element>
	<xsd:complexType name="CMSDataType" mixed="false">
		<xsd:complexContent mixed="false">
			<xsd:extension base="BaseElementOnlyType">
				<xsd:sequence>
					<xsd:element name="ContentNode" type="ContentNodeType" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

		ContentNode implementation structure

	-->
	<xsd:complexType name="ContentNodeType">
		<xsd:complexContent>
			<xsd:extension base="BaseElementOnlyType">
				<xsd:sequence>
					<xsd:element name="Attributes">
						<xsd:complexType mixed="false">
							<xsd:complexContent mixed="false">
								<xsd:extension base="BaseElementOnlyType">
									<xsd:choice minOccurs="0" maxOccurs="unbounded">
										<xsd:element name="Attribute" type="AttributeType"/>
									</xsd:choice>
								</xsd:extension>
							</xsd:complexContent>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="Relationships" minOccurs="0">
						<xsd:complexType mixed="false">
							<xsd:complexContent mixed="false">
								<xsd:extension base="BaseElementOnlyType">
									<xsd:sequence>
										<xsd:element name="Relationship" type="RelationshipType" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:extension>
							</xsd:complexContent>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
				<xsd:attribute name="contentType" type="xsd:string"/>
				<xsd:attribute name="contentId" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

		Attribute implementation structure

	-->
	<xsd:complexType name="AttributeType">
		<xsd:complexContent>
			<xsd:extension base="BaseElementOnlyType">
				<xsd:attributeGroup ref="KeyedObjectDef"/>
				<xsd:attributeGroup ref="InheritableDef"/>
				<xsd:attribute name="type" use="required" type="PrimitiveType"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

		Relationship implementation structure

	-->
	<xsd:complexType name="RelationshipType">
		<xsd:complexContent>
			<xsd:extension base="BaseElementOnlyType">
				<xsd:sequence>
					<xsd:element name="Destinations">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="Destination" minOccurs="0" maxOccurs="unbounded">
									<xsd:complexType>
										<xsd:complexContent>
											<xsd:extension base="BaseElementOnlyType">
												<xsd:attribute name="contentId"/>
											</xsd:extension>
										</xsd:complexContent>
									</xsd:complexType>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
				<xsd:attributeGroup ref="KeyedObjectDef"/>
				<xsd:attributeGroup ref="InheritableDef"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
</xsd:schema>

=== AnthonyCC/sf-temp-ui/projects/Tests/data/com/freshdirect/cms/application/service/xml/TestIdGeneration.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<cms:CMSDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cms="http://www.freshdirect.com/xsd/CMS"
	xsi:schemaLocation="http://www.freshdirect.com/xsd/CMS CMS.xsd">

	<cms:ContentTypeDef name="FooDefault">
		<cms:AttributeDefs>
			<cms:AttributeDef type="S" name="label" />
		</cms:AttributeDefs>
	</cms:ContentTypeDef>

	<cms:ContentTypeDef name="FooGenerateId" generateId="true">
		<cms:AttributeDefs>
			<cms:AttributeDef type="S" name="label" />
		</cms:AttributeDefs>
	</cms:ContentTypeDef>

	<cms:ContentTypeDef name="FooDontGenerateId" generateId="false">
		<cms:AttributeDefs>
			<cms:AttributeDef type="S" name="label" />
		</cms:AttributeDefs>
	</cms:ContentTypeDef>

</cms:CMSDef>

=== AnthonyCC/sf-temp-ui/projects/Tests/data/com/freshdirect/cms/search/TestDef2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<CMSDef xmlns="http://www.freshdirect.com/xsd/CMS"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.freshdirect.com/xsd/CMS CMS.xsd">

	<ContentTypeDef name="Foo">
		<AttributeDefs>
			<AttributeDef type="S" name="name" />
			<AttributeDef type="S" name="value" />
		</AttributeDefs>
	</ContentTypeDef>

	<ContentTypeDef name="SynTest">
		<AttributeDefs>
			<AttributeDef type="S" name="FULL_NAME" />
			<AttributeDef type="S" name="keywords" />
		</AttributeDefs>
	</ContentTypeDef>

</CMSDef>

=== AnthonyCC/sf-temp-ui/projects/CMS/src/com/freshdirect/cms/application/service/query/CmsQueryDef.xml
<?xml version="1.0" encoding="UTF-8"?>
<CMSDef xmlns="http://www.freshdirect.com/xsd/CMS" schemaLocation="http://www.freshdirect.com/xsd/CMS CMS.xsd">

	<ContentTypeDef name="CmsQueryFolder">
		<AttributeDefs>
			<AttributeDef type="S" name="name" readOnly="true"/>
		</AttributeDefs>
		<RelationshipDefs>
			<RelationshipDef name="subFolders" navigable="true" cardinality="Many" readOnly="true">
				<DestinationDef contentType="CmsQueryFolder" />
			</RelationshipDef>
			<RelationshipDef name="queries" navigable="true" cardinality="Many"  readOnly="true">
				<DestinationDef contentType="CmsQuery" />
				<DestinationDef contentType="CmsReport" />
			</RelationshipDef>
		</RelationshipDefs>
	</ContentTypeDef>

	<ContentTypeDef name="CmsReport">
		<AttributeDefs>
			<AttributeDef type="S" name="name" readOnly="true"/>
			<AttributeDef type="S" name="description" readOnly="true"/>
			<AttributeDef type="S" name="script" readOnly="true"/>
			<AttributeDef type="S" name="parameters" readOnly="true"/>
			<AttributeDef type="T" name="results" readOnly="true"/>
			<AttributeDef type="S" name="language" readOnly="true"/>
		</AttributeDefs>
	</ContentTypeDef>

	<ContentTypeDef name="CmsQuery">
		<AttributeDefs>
			<AttributeDef type="S" name="name" readOnly="true"/>
			<AttributeDef type="S" name="description" readOnly="true"/>
			<AttributeDef type="S" name="script" readOnly="true"/>
			<AttributeDef type="S" name="language" readOnly="true"/>
		</AttributeDefs>
		<RelationshipDef name="results" navigable="true" cardinality="Many" readOnly="true"/>
	</ContentTypeDef>

</CMSDef>

=== AnthonyCC/sf-temp-ui/projects/Tests/data/com/freshdirect/cms/application/service/xml/TestDefinition.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<cms:CMSDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cms="http://www.freshdirect.com/xsd/CMS"
	xsi:schemaLocation="http://www.freshdirect.com/xsd/CMS CMS.xsd">

	<cms:ContentTypeDef name="Foo">
		<cms:AttributeDefs>
			<cms:AttributeDef type="S" name="label" />
			<cms:AttributeDef type="DT" name="date" />
			<cms:EnumDef type="I" name="enum">
				<cms:EnumValue value="10" label="ten"/>
				<cms:EnumValue value="20" label="twenty"/>
			</cms:EnumDef>
		</cms:AttributeDefs>
		<cms:RelationshipDefs>
			<cms:RelationshipDef name="children" navigable="true" cardinality="Many">
				<cms:DestinationDef contentType="Foo" />
			</cms:RelationshipDef>
		</cms:RelationshipDefs>
	</cms:ContentTypeDef>

</cms:CMSDef>

=== AnthonyCC/sf-temp-ui/projects/CMS/src/com/freshdirect/cms/resource/CMSFormDef.xml
<?xml version="1.0" encoding="UTF-8"?>
<CMSDef xmlns="http://www.freshdirect.com/xsd/CMS" schemaLocation="http://www.freshdirect.com/xsd/CMS CMS.xsd">

	<ContentTypeDef name="CmsFolder">
		<AttributeDefs>
			<AttributeDef type="S" name="name" />
		</AttributeDefs>
		<RelationshipDefs>
			<RelationshipDef name="subFolders" navigable="true" cardinality="Many">
				<DestinationDef contentType="CmsFolder" />
			</RelationshipDef>
			<RelationshipDef name="editors" navigable="true" cardinality="Many">
				<DestinationDef contentType="CmsEditor" />
			</RelationshipDef>
		</RelationshipDefs>
	</ContentTypeDef>


	<ContentTypeDef name="CmsEditor">
		<AttributeDefs>
			<AttributeDef type="S" name="contentType" />
		</AttributeDefs>
		<RelationshipDefs>
			<RelationshipDef name="pages" navigable="true" cardinality="Many">
				<DestinationDef contentType="CmsPage" />
			</RelationshipDef>
		</RelationshipDefs>
	</ContentTypeDef>

	<ContentTypeDef name="CmsPage">
		<AttributeDefs>
			<AttributeDef type="S" name="title" />
		</AttributeDefs>
		<RelationshipDefs>
			<RelationshipDef name="sections" navigable="true" cardinality="Many">
				<DestinationDef contentType="CmsSection" />
			</RelationshipDef>
		</RelationshipDefs>
	</ContentTypeDef>

	<ContentTypeDef name="CmsSection">
		<AttributeDefs>
			<AttributeDef type="S" name="title" />
		</AttributeDefs>
		<RelationshipDefs>
			<RelationshipDef name="fields" navigable="true" cardinality="Many">
				<DestinationDef contentType="CmsField" />
				<DestinationDef contentType="CmsGridField" />
				<DestinationDef contentType="CmsCustomField" />
				<DestinationDef contentType="CmsMultiColumnField" />
			</RelationshipDef>
		</RelationshipDefs>
	</ContentTypeDef>

	<ContentTypeDef name="CmsField">
		<AttributeDefs>
			<AttributeDef type="S" name="attribute" />
		</AttributeDefs>
	</ContentTypeDef>

	<ContentTypeDef name="CmsCustomField">
		<AttributeDefs>
			<AttributeDef type="S" name="attribute" />
			<AttributeDef type="S" name="component" />
		</AttributeDefs>
	</ContentTypeDef>
		
	<ContentTypeDef name="CmsGridField">
		<AttributeDefs>
			<AttributeDef type="S" name="attribute" />
		</AttributeDefs>
		<RelationshipDefs>
			<RelationshipDef name="columns" navigable="true" cardinality="Many">
				<DestinationDef contentType="CmsField" />
			</RelationshipDef>
		</RelationshipDefs>
	</ContentTypeDef>
	
	<ContentTypeDef name="CmsMultiColumnField">
		<AttributeDefs>
			<AttributeDef type="S" name="attribute" />
		</AttributeDefs>
		<RelationshipDefs>
			<RelationshipDef name="columns" navigable="true" cardinality="Many">
				<DestinationDef contentType="CmsField" />
			</RelationshipDef>
		</RelationshipDefs>
	</ContentTypeDef>

</CMSDef>
